# Generated by Django 5.1.3 on 2024-11-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_remove_advert_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='user',
        ),
    ]
