# Generated by Django 5.1.3 on 2024-11-21 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advert', '0002_remove_advert_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Araba',
            fields=[
                ('advert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advert.advert')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('yil', models.PositiveIntegerField()),
                ('kilometre', models.PositiveIntegerField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renk', models.CharField(max_length=30)),
                ('motor_hacmi', models.PositiveIntegerField()),
                ('yakit_turu', models.CharField(choices=[('Benzin', 'Benzin'), ('Dizel', 'Dizel'), ('Elektrik', 'Elektrik'), ('Hibrit', 'Hibrit')], max_length=20)),
                ('vites_turu', models.CharField(choices=[('Manuel', 'Manuel'), ('Otomatik', 'Otomatik'), ('Yarı Otomatik', 'Yarı Otomatik')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('advert.advert',),
        ),
        migrations.CreateModel(
            name='Ev',
            fields=[
                ('advert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advert.advert')),
                ('oda_sayisi', models.PositiveIntegerField()),
                ('metrekare', models.PositiveIntegerField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kat', models.PositiveIntegerField()),
                ('bina_yasi', models.PositiveIntegerField()),
                ('isinma_tipi', models.CharField(choices=[('Doğalgaz', 'Doğalgaz'), ('Elektrik', 'Elektrik'), ('Soba', 'Soba'), ('Merkezi', 'Merkezi')], max_length=20)),
                ('balkon', models.BooleanField(default=False)),
                ('adres', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('advert.advert',),
        ),
    ]
