# Generated by Django 5.1.3 on 2024-12-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='araba',
            name='fiyat',
        ),
        migrations.RemoveField(
            model_name='ev',
            name='fiyat',
        ),
    ]
