# Generated by Django 5.1.3 on 2024-12-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_araba_fiyat_remove_ev_fiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='araba',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ev',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
